### ISSUE TITLE
AssertionError à l'execution

### ISSUE THREAD

**Issue by adrienandrem** [rene-d/cadastre#1]
Bonjour,

l’exécution s’interrompt sur une `AssertionError` avec le fichier `Fichier national FANTOIR (situation avril 2021).zip`
téléchargé depuis https://www.data.gouv.fr/fr/datasets/fichier-fantoir-des-voies-et-lieux-dits

```
python fantoir.py Fichier\ national\ FANTOIR\ \(situation\ avril\ 2021\).zip 
Fichier national FANTOIR (situation avril 2021).zip: 8240924 lignes [07:08, 19234.50 lignes/s]
Traceback (most recent call last):
  File "fantoir.py", line 266, in <module>
    main()
  File "fantoir.py", line 249, in main
    assert i > 0
AssertionError
```

**Comment by rene-d** [comment]
Bonjour,

L'erreur se produit sur l'enregistrement final (la dernière ligne du fichier). Si je me réfère à mon [commentaire dans le code](https://github.com/rene-d/cadastre/blob/master/fantoir.py#L127), le format de cet enregistrement est non documenté, donc la supposition de son format ne correspond plus au dernier fichier FANTOIR. Et je n'avais pas cherché plus loin.

En 2018 c'était:
`80418781093705780047100000000`

En avril 2021 il y a:
`82592771093706082221060000000`

Il y a donc un chiffre utilisé (ou non 0) en plus, le `6` le plus à droite.

`8222106` et `8259277` sont du même ordre de grandeur que le nombre de lignes (8240925 en avril 2021), mais pas tout à fait. Quant à `10937060` c'est plus mystérieux.

Quoi qu'il en soit j'ai poussé la correction qui permet de lire le fichier d'avril 2021.

Merci pour l'intérêt :)

**Comment by adrienandrem** [comment]
Je confirme que ça fonctionne ici, merci.
